/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import atm.simulator.system.classes.Connect;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author jessi
 */
public class Transfer extends javax.swing.JFrame {

    final JDialog dialog = new JDialog();
    int balance, id, amount;
    String account_name, account_number, bsb;
    Connect conn = new Connect();
    PreparedStatement st;
    ResultSet rs;
    
    /**
     * Creates new form Transfer
     */
    public Transfer(int user_id) {
        initComponents();
        this.setLocationRelativeTo(null);
        dialog.setAlwaysOnTop(true);   
        id = user_id;
    }
    
    private boolean checkFieldsFilled() {
        if (t_account_name.getText().trim().equals("") || t_bsb.getText().trim().equals("") ||
                    t_account_number.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(dialog, "Please Complete All Fields");
            return false;
        }
        return true;
    }
    
    private int getBalance(int id) {
        int balance = -1000;
        try {
            String sql = "SELECT * FROM accounts A, mappings B, users C "
                        + "WHERE A.account_id = B.account_id "
                        + "AND B.user_id = C.user_id "
                        + "AND C.user_id = ?";
            st = conn.getConnection().prepareStatement(sql);
            st.setInt(1, id);
            rs = st.executeQuery();
            
            if (rs.next()) {
                balance = rs.getInt("balance");
            } 
        } catch(SQLException e) {
            System.err.print("There was an error" + e);
        }
        return balance;
    }
    
    private int getDepositId(String account_number) {
        int id = -1;
        try {
            String sql = "SELECT * FROM users A, mappings B, accounts C "
                        + "WHERE A.user_id = B.user_id "
                        + "AND B.account_id = C.account_id "
                        + "AND C.account_no = ?";
            st = conn.getConnection().prepareStatement(sql);
            st.setString(1, account_number);
            rs = st.executeQuery();
            
            if (rs.next()) {
                id = rs.getInt("user_id");
            } 
        } catch(SQLException e) {
            System.err.print("There was an error" + e);
        }
        return id;
    }
    
    private void depositMoney(String account_number, String bsb, int amount) {
        int deposit_balance;
        int depositId = getDepositId(account_number);
        try {
            String sql = "SELECT * FROM accounts A, mappings B, users C "
                        + "WHERE A.account_id = B.account_id "
                        + "AND B.user_id = C.user_id "
                        + "AND C.user_id = ?";
            st = conn.getConnection().prepareStatement(sql);
            st.setInt(1, depositId);
            rs = st.executeQuery();
            
            if (rs.next()) {
                deposit_balance = rs.getInt("balance");
                deposit_balance += amount;
                updateBalance(depositId, deposit_balance);
            } 
        } catch(SQLException e) {
            System.err.print("There was an error" + e);
        }
    }
    
    private void updateBalance(int id, int amount) {
            
        // Update balance
        String sql = "UPDATE accounts A, mappings B, users C "
                    + "SET balance = ? "
                    + "WHERE A.account_id = B.account_id "
                    + "AND B.user_id = C.user_id "
                    + "AND C.user_id = ?";
        try {
            st = conn.getConnection().prepareStatement(sql);
            st.setInt(1, amount);
            st.setInt(2, id);
            st.executeUpdate();
        } catch (SQLException e) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_account_number = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_account_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_bsb = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        t_amount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pay Someone");

        jLabel2.setText("Account Number");

        t_account_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_account_numberActionPerformed(evt);
            }
        });

        jLabel3.setText("Account Name");

        t_account_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_account_nameActionPerformed(evt);
            }
        });

        jLabel4.setText("BSB");

        t_bsb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_bsbActionPerformed(evt);
            }
        });

        jButton1.setText("PAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Amount $");

        t_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_amountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_amount)
                            .addComponent(t_bsb, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_account_name)
                            .addComponent(t_account_number))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_account_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_bsb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_account_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_account_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_account_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_account_numberActionPerformed

    private void t_account_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_account_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_account_nameActionPerformed

    private void t_bsbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_bsbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bsbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (checkFieldsFilled()) {
            balance = getBalance(id);
            account_number = t_account_number.getText();
            account_name = t_account_name.getText();
            bsb = t_bsb.getText();
            amount = Integer.parseInt(t_amount.getText());
            
            if (amount > balance) {
                JOptionPane.showMessageDialog(dialog, "Insufficient Funds");
            } else {
                // Update balance
                balance -= amount;
                updateBalance(id, balance);
                // Deposit money
                depositMoney(account_number, bsb, amount);
                JOptionPane.showMessageDialog(dialog, "Successful Deposit");
            }
            this.dispose();
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_amountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer(int id).setVisible(true);
            }
        }); */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t_account_name;
    private javax.swing.JTextField t_account_number;
    private javax.swing.JTextField t_amount;
    private javax.swing.JTextField t_bsb;
    // End of variables declaration//GEN-END:variables
}
